// <auto-generated />
using Fabrica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fabrica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260207005452_AddMateriais")]
    partial class AddMateriais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Fabrica.Models.Acessorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acessorio", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Disco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrossuraMm")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaioMm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Disco", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.NivelAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NivelAcesso", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelAcessoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NivelAcessoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Usuario", b =>
                {
                    b.HasOne("Fabrica.Models.NivelAcesso", "NivelAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("NivelAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelAcesso");
                });

            modelBuilder.Entity("Fabrica.Models.NivelAcesso", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
