// <auto-generated />
using Fabrica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fabrica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407195000_AddItens")]
    partial class AddItens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Fabrica.Models.Acessorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acessorio", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Disco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrossuraMm")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaioMm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Disco", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscoTampaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiTampa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscoId");

                    b.HasIndex("DiscoTampaId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.ItemAcessorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcessorioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcessorioId");

                    b.HasIndex("ItemId", "AcessorioId")
                        .IsUnique();

                    b.ToTable("ItemAcessorio", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.NivelAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NivelAcesso", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelAcessoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NivelAcessoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Item", b =>
                {
                    b.HasOne("Fabrica.Models.Disco", "Disco")
                        .WithMany()
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabrica.Models.Disco", "DiscoTampa")
                        .WithMany()
                        .HasForeignKey("DiscoTampaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Disco");

                    b.Navigation("DiscoTampa");
                });

            modelBuilder.Entity("Fabrica.Models.ItemAcessorio", b =>
                {
                    b.HasOne("Fabrica.Models.Acessorio", "Acessorio")
                        .WithMany()
                        .HasForeignKey("AcessorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabrica.Models.Item", "Item")
                        .WithMany("ItemAcessorios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acessorio");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Fabrica.Models.Usuario", b =>
                {
                    b.HasOne("Fabrica.Models.NivelAcesso", "NivelAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("NivelAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelAcesso");
                });

            modelBuilder.Entity("Fabrica.Models.Item", b =>
                {
                    b.Navigation("ItemAcessorios");
                });

            modelBuilder.Entity("Fabrica.Models.NivelAcesso", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
