// <auto-generated />
using System;
using Fabrica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fabrica.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Fabrica.Models.Acessorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Acessorio", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Disco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("GrossuraMm")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PesoUnitarioKg")
                        .HasPrecision(10, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("RaioMm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Disco", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.EstoqueMovimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AcessorioId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ConsumoAutomatico")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCriacaoUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(14, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AcessorioId");

                    b.HasIndex("DataCriacaoUtc");

                    b.HasIndex("DiscoId");

                    b.HasIndex("ItemId");

                    b.ToTable("EstoqueMovimento", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DiscoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DiscoTampaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PossuiTampa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DiscoId");

                    b.HasIndex("DiscoTampaId");

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.ItemAcessorio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AcessorioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AcessorioId");

                    b.HasIndex("ItemId", "AcessorioId")
                        .IsUnique();

                    b.ToTable("ItemAcessorio", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.NivelAcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NivelAcesso", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataPedido");

                    b.HasIndex("Status");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.PedidoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(14, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PedidoId");

                    b.HasIndex("PedidoId", "ItemId")
                        .IsUnique();

                    b.ToTable("PedidoItem", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("NivelAcessoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NivelAcessoId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Fabrica.Models.EstoqueMovimento", b =>
                {
                    b.HasOne("Fabrica.Models.Acessorio", "Acessorio")
                        .WithMany()
                        .HasForeignKey("AcessorioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fabrica.Models.Disco", "Disco")
                        .WithMany()
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Fabrica.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Acessorio");

                    b.Navigation("Disco");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Fabrica.Models.Item", b =>
                {
                    b.HasOne("Fabrica.Models.Disco", "Disco")
                        .WithMany()
                        .HasForeignKey("DiscoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabrica.Models.Disco", "DiscoTampa")
                        .WithMany()
                        .HasForeignKey("DiscoTampaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Disco");

                    b.Navigation("DiscoTampa");
                });

            modelBuilder.Entity("Fabrica.Models.ItemAcessorio", b =>
                {
                    b.HasOne("Fabrica.Models.Acessorio", "Acessorio")
                        .WithMany()
                        .HasForeignKey("AcessorioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabrica.Models.Item", "Item")
                        .WithMany("ItemAcessorios")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acessorio");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Fabrica.Models.Pedido", b =>
                {
                    b.HasOne("Fabrica.Models.Cliente", "Cliente")
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Fabrica.Models.PedidoItem", b =>
                {
                    b.HasOne("Fabrica.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Fabrica.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Fabrica.Models.Usuario", b =>
                {
                    b.HasOne("Fabrica.Models.NivelAcesso", "NivelAcesso")
                        .WithMany("Usuarios")
                        .HasForeignKey("NivelAcessoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelAcesso");
                });

            modelBuilder.Entity("Fabrica.Models.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Fabrica.Models.Item", b =>
                {
                    b.Navigation("ItemAcessorios");
                });

            modelBuilder.Entity("Fabrica.Models.NivelAcesso", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Fabrica.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
